=== dherutskyi/castor_files/cad-unit.json
{
  "definitions": {
    "uuid_identifier" : {
      "type": "string",
      "pattern": "^[0-9a-fA-F]{8}\\-[0-9a-fA-F]{4}\\-[0-9a-fA-F]{4}\\-[0-9a-fA-F]{4}\\-[0-9a-fA-F]{12}$"
    },
    "measure_unit" : {
      "type": "string",
      "pattern": "^(mm|cm|m|inch|feet)$"
    },
    "vec_3" : {
      "type": "array",
      "items": { "type":"integer" }
    },
    "property_item" : {
      "type" : "object",
      "properties": {
        "name": {"type": "string"},
        "value": {"type": "integer"}
      },
      "required": ["name", "value"]
    },
    "file" : {
      "type": "object",
      "properties" : {
        "format": {"type":"string"},
        "storage_ref": {"$ref" : "#/definitions/uuid_identifier"}
      },
      "required":["format", "storage_ref"]
    },
    "material" : {
      "type" : "object",
      "properties" : {
        "id": {"type" :"integer"},
        "name": {"type": "string"},
        "props": {"type": "array", "items" : {"$ref": "#/definitions/property_item"}}
      }
    },
    "cad_metadata" : {
      "type":"object",
      "properties" : {
        "units": {"$ref" : "#/definitions/measure_unit"},
        "volume": {"type" : "integer"},
        "bounding_box": {"$ref" : "#/definitions/vec_3"},
        "materials" : {"type" : "array", "items" : { "$ref" : "#/definitions/material"}}
      },
      "required": ["units", "volume","bounding_box","materials"]
    }
  },
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://raw.githubusercontent.com/dherutskyi/castor_files/master/cad-unit.json",
  "type": "object",
  "title": "The Root Schema",
  "properties": {
    "projetc_id": {"$ref" : "#/definitions/uuid_identifier"},
    "cad_file": { "$ref" : "#/definitions/file"},
    "intermediate_cad_file": { "$ref" : "#/definitions/file"},
    "metadata": { "$ref" : "#/definitions/cad_metadata"}
  },
  "required": ["projetc_id", "cad_file"]
}

=== dherutskyi/castor_files/examples/cad-unit.json
{
    "$schema" : "https://raw.githubusercontent.com/dherutskyi/castor_files/master/api/schemas/cad-unit.json",
    "projetc_id": "2d801ae0-d3ca-11e9-bb65-2a2ae2dbcce4",
    "cad_file": {
        "format": "iges",
        "storage_ref": "2d801df6-d3ca-11e9-bb65-2a2ae2dbcce4"
    },
    "intermediate_cad_file": {
        "format": "stl",
        "storage_ref": "2d802080-d3ca-11e9-bb65-2a2ae2dbcce4"
    },
    "metadata": {
        "units": "mm",
        "volume": 0,
        "bounding_box": [1, 1, 1],
        "materials": [
            {
                "id": 1,
                "name": "material_name_string",
                "props": [
                    {
                        "name": "prop_name",
                        "value": 1
                    }
                ]
            }
        ]
    }
}
